In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
AZ_Teachers = pd.read_csv("staff-Export_PowerschoolDownload.csv", encoding='latin-1')

In [3]:
AZ_Teachers

,TEACHERS.SchoolID,TEACHERS.TeacherNumber,TEACHERS.Last_Name,TEACHERS.First_Name,TEACHERS.Middle_Name,TEACHERS.Email_Addr,TEACHERS.Title,TEACHERS.Status,Staff_Code,TEACHERS.dcid
0,0,kmck,McKinstry,Kathy,NaN,kathy.mckinstry@pearson.com,NaN,2,1,1
1,0,9000,Vierkoetter,Elizabeth,NaN,liz.vierkoetter@vertexeducation.com,Executive Assistant,1,2,2
2,0,9001,Adams,Brandi,M,brandi.adams@legacytraditional.org,School Support Systems VP,2,51,51
3,0,1001,Hackett,Janisha,NaN,janisha.hackett@legacytraditional.org,Human Resources Director,2,101,101
4,250,1,Moss,Chelsea,NaN,NaN,NaN,2,102,102
...,...,...,...,...,...,...,...,...,...,...
8804,450,8967,Ross,Hallie,NaN,hallie.ross@legacytraditional.org,SPED SLP (Contractor),1,16155,17405
8805,450,8968,Johnson,Jessi,NaN,jessi.johnson@legacytraditional.org,SPED SLP (Contractor),1,16156,17406
8806,300,8969,Hartvigsen,Abiagail,NaN,abiagail.hartvigsen@legacytraditional.org,SPED SLPA (Contractor),1,16157,17407
8807,600,8965,Dunham,Christy,NaN,christy.dunham@legacytraditional.org,SPED SLP (Contractor),1,16153,17408
8808,800,7475,Wiebelhaus,Chad,NaN,chad.wiebelhaus@legacytraditional.org,Facilities Manager,1,13108,17409

In [4]:
AZ_Teachers['TEACHERS.Status'].value_counts()

2    4897
1    2769
0    1143
Name: TEACHERS.Status, dtype: int64

In [5]:
AZ_ActiveTeachers = AZ_Teachers.loc[(AZ_Teachers["TEACHERS.Status"] == 1)]

In [6]:
AZ_ActiveTeachers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2769 entries, 1 to 8808
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TEACHERS.SchoolID       2769 non-null   int64
 1   TEACHERS.TeacherNumber  2769 non-null   object
 2   TEACHERS.Last_Name      2769 non-null   object
 3   TEACHERS.First_Name     2769 non-null   object
 4   TEACHERS.Middle_Name    170 non-null    object
 5   TEACHERS.Email_Addr     2727 non-null   object
 6   TEACHERS.Title          2758 non-null   object
 7   TEACHERS.Status         2769 non-null   int64
 8   Staff_Code              2769 non-null   int64
 9   TEACHERS.dcid           2769 non-null   int64
dtypes: int64(4), object(6)
memory usage: 238.0+ KB

In [7]:
AZ_RawStaff = AZ_ActiveTeachers[['TEACHERS.SchoolID','TEACHERS.TeacherNumber','TEACHERS.Email_Addr','TEACHERS.First_Name','TEACHERS.Last_Name','TEACHERS.Title']]

In [8]:
AZ_RawStaff

,TEACHERS.SchoolID,TEACHERS.TeacherNumber,TEACHERS.Email_Addr,TEACHERS.First_Name,TEACHERS.Last_Name,TEACHERS.Title
1,0,9000,liz.vierkoetter@vertexeducation.com,Elizabeth,Vierkoetter,Executive Assistant
8,100,1007,Malika.Khaaliq@legacytraditional.org,Malika,Khaaliq,Kinder Teacher
12,100,1011,Cheryl.Cardinal@legacytraditional.org,Cheryl,Cardinal,4th Grade Teacher
14,100,1013,Shawna.Bennett@legacytraditional.org,Shawna,Bennett,5th Grade Teacher
15,100,1014,cambria.brownfield@legacytraditional.org,Cambria,Brownfield,JH Eng/Lit Teacher
...,...,...,...,...,...,...
8804,450,8967,hallie.ross@legacytraditional.org,Hallie,Ross,SPED SLP (Contractor)
8805,450,8968,jessi.johnson@legacytraditional.org,Jessi,Johnson,SPED SLP (Contractor)
8806,300,8969,abiagail.hartvigsen@legacytraditional.org,Abiagail,Hartvigsen,SPED SLPA (Contractor)
8807,600,8965,christy.dunham@legacytraditional.org,Christy,Dunham,SPED SLP (Contractor)
8808,800,7475,chad.wiebelhaus@legacytraditional.org,Chad,Wiebelhaus,Facilities Manager

<H4> Username is '1_' + TeacherNumber/Staff_ID, <br>
    Password is 'TeacherNumber' + 'Legacy!2021' (for now) <br>
    Role depends on Teacher (STL for Instructional Coaches) <br>
    ...+ 2 extra data fields

In [9]:
AZ_RawStaff.rename(columns={'TEACHERS.SchoolID': 'School_id', 'TEACHERS.TeacherNumber': 'Staff_id', 'TEACHERS.Email_Addr': 'Staff_email', 'TEACHERS.First_Name': 'First_name', 'STUDENTS.First_Name': 'First_Name', 'TEACHERS.Last_Name': 'Last_name', 'TEACHERS.Title': 'Title'}, inplace=True)

C:\Users\lauren.goldfish\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [12]:
AZ_RawStaff

,School_id,Staff_id,Staff_email,First_name,Last_name,Title
1,0,9000,liz.vierkoetter@vertexeducation.com,Elizabeth,Vierkoetter,Executive Assistant
8,100,1007,Malika.Khaaliq@legacytraditional.org,Malika,Khaaliq,Kinder Teacher
12,100,1011,Cheryl.Cardinal@legacytraditional.org,Cheryl,Cardinal,4th Grade Teacher
14,100,1013,Shawna.Bennett@legacytraditional.org,Shawna,Bennett,5th Grade Teacher
15,100,1014,cambria.brownfield@legacytraditional.org,Cambria,Brownfield,JH Eng/Lit Teacher
...,...,...,...,...,...,...
8804,450,8967,hallie.ross@legacytraditional.org,Hallie,Ross,SPED SLP (Contractor)
8805,450,8968,jessi.johnson@legacytraditional.org,Jessi,Johnson,SPED SLP (Contractor)
8806,300,8969,abiagail.hartvigsen@legacytraditional.org,Abiagail,Hartvigsen,SPED SLPA (Contractor)
8807,600,8965,christy.dunham@legacytraditional.org,Christy,Dunham,SPED SLP (Contractor)
8808,800,7475,chad.wiebelhaus@legacytraditional.org,Chad,Wiebelhaus,Facilities Manager

In [13]:
AZ_RawStaff['Username'] = '1_' + AZ_RawStaff['Staff_id'].astype(str)

C:\Users\LAUREN~1.GOL\AppData\Local\Temp/ipykernel_8292/3257977958.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AZ_RawStaff['Username'] = '1_' + AZ_RawStaff['Staff_id'].astype(str)

In [14]:
AZ_RawStaff['Password'] = AZ_RawStaff['Staff_id'].astype(str) + 'Legacy!2022'

C:\Users\LAUREN~1.GOL\AppData\Local\Temp/ipykernel_8292/4047604402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AZ_RawStaff['Password'] = AZ_RawStaff['Staff_id'].astype(str) + 'Legacy!2022'

In [15]:
AZ_RawStaff

,School_id,Staff_id,Staff_email,First_name,Last_name,Title,Username,Password
1,0,9000,liz.vierkoetter@vertexeducation.com,Elizabeth,Vierkoetter,Executive Assistant,1_9000,9000Legacy!2022
8,100,1007,Malika.Khaaliq@legacytraditional.org,Malika,Khaaliq,Kinder Teacher,1_1007,1007Legacy!2022
12,100,1011,Cheryl.Cardinal@legacytraditional.org,Cheryl,Cardinal,4th Grade Teacher,1_1011,1011Legacy!2022
14,100,1013,Shawna.Bennett@legacytraditional.org,Shawna,Bennett,5th Grade Teacher,1_1013,1013Legacy!2022
15,100,1014,cambria.brownfield@legacytraditional.org,Cambria,Brownfield,JH Eng/Lit Teacher,1_1014,1014Legacy!2022
...,...,...,...,...,...,...,...,...
8804,450,8967,hallie.ross@legacytraditional.org,Hallie,Ross,SPED SLP (Contractor),1_8967,8967Legacy!2022
8805,450,8968,jessi.johnson@legacytraditional.org,Jessi,Johnson,SPED SLP (Contractor),1_8968,8968Legacy!2022
8806,300,8969,abiagail.hartvigsen@legacytraditional.org,Abiagail,Hartvigsen,SPED SLPA (Contractor),1_8969,8969Legacy!2022
8807,600,8965,christy.dunham@legacytraditional.org,Christy,Dunham,SPED SLP (Contractor),1_8965,8965Legacy!2022
8808,800,7475,chad.wiebelhaus@legacytraditional.org,Chad,Wiebelhaus,Facilities Manager,1_7475,7475Legacy!2022

<H4> Last Three Columns: <br> 
    * Role: STL for all specific roles <br>
    * ext.emp_staff_username and ext.vertexEmp<br>

In [ ]:
df_mClassStaffFile.to_csv('Legacy_Traditional_Schools_Arizona_staff.csv', index=False, encoding='utf-8')